version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tinyurl_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin_password

  redis:
    image: redis
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    restart: always

  backend:
    build:
      context: ./TinyURL
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tinyurl_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin_password
      SPRING_DATA_REDIS_HOST: redis
    depends_on:
      - redis
      - db

  frontend:
    build:
      context: ./TinyURL_Frontend/tiny-url-frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend


